name: Deploy SoundMap

on:
# runs on pushes targeting the default branch
  push:
    branches: ["main"]
  #allows running this workflow manually from actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
# allow only one concurrent deployment
# skipping runs queued between the run in-progress and latest queued
# does not cancel in-progress runs to allow these production deployments to complete
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
